alter session set "_ORACLE_SCRIPT"=true;

 SELECT * FROM user_users;

CREATE SMALLFILE TABLESPACE BET_ITM
  DATAFILE 'C:\BDA\BetItm.dbf' SIZE 500M,
           'C:\BDA\BetItm2.dbf' SIZE 500M;
 
   
  CREATE BIGFILE TABLESPACE BET_AUDITING
  DATAFILE 'C:\BDA\BET_AUDITING.dbf'   SIZE 2G;
  
  
CREATE UNDO TABLESPACE UNDO_TBS datafile 'C:\BDA\UndoTs.db' size 500M;
  
CREATE USER MAINDEVELOPER IDENTIFIED BY MAINDEVELOPER;

CREATE USER WEB_MAINUSER IDENTIFIED BY WEB_USER;

CREATE USER ADMINDB IDENTIFIED BY ADMINDB;

CREATE USER MAINANALYST IDENTIFIED BY MAINANALYST;

CREATE USER MAININFRAESTRUCTURE IDENTIFIED BY INFRAESTRUCTURESUPP;

CREATE USER REPORTMAKER IDENTIFIED BY REPORTMAKER;

CREATE USER AUDITUSER IDENTIFIED BY AUDITUSER;

CREATE USER WEB_USER2 IDENTIFIED BY WEB_USER2;

CREATE USER DEVELOPERSUPPORT IDENTIFIED BY analyst2;

CREATE USER SUPPORTINFRAESTRUCTURE IDENTIFIED BY auditor2;

  
  CREATE PROFILE DEVELOPER LIMIT
		SESSIONS_PER_USER 1
		CONNECT_TIME 60
        IDLE_TIME 30
		FAILED_LOGIN_ATTEMPTS 5
		PASSWORD_LIFE_TIME 90;


CREATE PROFILE WEB_APPLICATION LIMIT
		SESSIONS_PER_USER 5
		CONNECT_TIME UNLIMITED
        IDLE_TIME UNLIMITED
		FAILED_LOGIN_ATTEMPTS 2
		PASSWORD_LIFE_TIME 30;

CREATE PROFILE DBA_ADMIN LIMIT
		SESSIONS_PER_USER 1
		CONNECT_TIME 30
        IDLE_TIME UNLIMITED
		FAILED_LOGIN_ATTEMPTS 2
		PASSWORD_LIFE_TIME 30;

CREATE PROFILE ANALYST LIMIT
		SESSIONS_PER_USER 1
        CONNECT_TIME 30
		IDLE_TIME 5
		FAILED_LOGIN_ATTEMPTS 3
		PASSWORD_LIFE_TIME 30
        PASSWORD_GRACE_TIME 3;

CREATE PROFILE SUPPORT_III LIMIT
		SESSIONS_PER_USER 1
        CONNECT_TIME 240
		IDLE_TIME 5
		FAILED_LOGIN_ATTEMPTS 3
		PASSWORD_LIFE_TIME 20
        PASSWORD_GRACE_TIME 3;
   

CREATE PROFILE REPORTER LIMIT
		SESSIONS_PER_USER 1
		CONNECT_TIME 90
        IDLE_TIME 15
		FAILED_LOGIN_ATTEMPTS 4
		PASSWORD_LIFE_TIME UNLIMITED
        PASSWORD_GRACE_TIME 5;

CREATE PROFILE AUDITOR LIMIT
		SESSIONS_PER_USER 1
		CONNECT_TIME 90
		IDLE_TIME 15
		FAILED_LOGIN_ATTEMPTS 4
		PASSWORD_LIFE_TIME UNLIMITED
        PASSWORD_GRACE_TIME 5;



ALTER USER MAINDEVELOPER 
PROFILE DEVELOPER; 
GRANT CREATE SESSION TO MAINDEVELOPER;

ALTER USER WEB_MAINUSER 
PROFILE WEB_APPLICATION;
GRANT CREATE SESSION TO WEB_MAINUSER;

ALTER USER ADMINDB 
PROFILE DBA_ADMIN;
GRANT CREATE SESSION TO ADMINDB;

ALTER USER MAINANALYST 
PROFILE ANALYST;
GRANT CREATE SESSION TO MAINANALYST;

ALTER USER MAININFRAESTRUCTURE 
PROFILE SUPPORT_III;
GRANT CREATE SESSION TO MAININFRAESTRUCTURE;


ALTER USER REPORTMAKER 
PROFILE REPORTER;
GRANT CREATE SESSION TO REPORTMAKER;

ALTER USER AUDITUSER 
PROFILE AUDITOR;
GRANT CREATE SESSION TO AUDITUSER;


ALTER USER DEVELOPERSUPPORT 
PROFILE DEVELOPER;
GRANT CREATE SESSION TO DEVELOPERSUPPORT;


ALTER USER WEB_USER2 
PROFILE WEB_APPLICATION;
GRANT CREATE SESSION TO WEB_USER2;


ALTER USER SUPPORTINFRAESTRUCTURE 
PROFILE DEVELOPER;
GRANT CREATE SESSION TO EVELIODBA;


SELECT * FROM USER_USERS;

CREATE TABLE COUNTRY (
 ID INT generated always as identity,
ID_COUNTRY NUMBER(10) NOT NULL,
COUNTRY_NAME VARCHAR2(100) NOT NULL,
active varchar2(1) not null,
PREFIX VARCHAR2(4),
CONSTRAINT PK_ID_COUNTRY PRIMARY KEY (ID_COUNTRY)
)TABLESPACE BET_ITM; 


CREATE TABLE DEPARTMENT (
 ID INT generated always as identity,
ID_DEPARTMENT NUMBER(10) NOT NULL,
DEPARTMENT_NAME VARCHAR2(100) NOT NULL,
active varchar2(1) not null,
FK_COUNTRY INT NOT NULL,
CONSTRAINT PK_ID_DEPARTMENT PRIMARY KEY (ID_DEPARTMENT),
FOREIGN KEY (FK_COUNTRY) REFERENCES COUNTRY (ID_COUNTRY)
)TABLESPACE BET_ITM ;

CREATE TABLE CITY (
 ID INT generated always as identity,
ID_CITY NUMBER(10) NOT NULL,
CITY_NAME VARCHAR2(100) NOT NULL,
active varchar2(1) not null,
FK_DEPARTMENT INT NOT NULL,
CONSTRAINT PK_ID_CITY PRIMARY KEY (ID_CITY),
FOREIGN KEY (FK_DEPARTMENT) REFERENCES DEPARTMENT (ID_DEPARTMENT)
)TABLESPACE BET_ITM;

CREATE TABLE DOCUMENT_USER
(
 ID INT generated always as identity,
ID_DOCUMENT NUMBER(10) NOT NULL,
FIRSTNAME VARCHAR2(30)NOT NULL,
LASTNAME VARCHAR2(30)NOT NULL,
GENDER VARCHAR2(10) NOT NULL,
DOCUMENT_NUMBER NUMBER(10) NOT NULL,
ISSUE_PLACE VARCHAR2(20) NOT NULL,
ISSUE_DATE TIMESTAMP NOT NULL,
NATIONALITY VARCHAR2(20) NOT NULL,
BIRTHDAY TIMESTAMP NOT NULL,
EMAIL VARCHAR2(100) NOT NULL,
PASSWORDUSER VARCHAR2(100) NOT NULL,
ADDRESS_HOUSE VARCHAR2(100) NOT NULL,
FK_DEPARTMENT_HOUSE INT NOT NULL,
FK_CITY INT NOT NULL,
POSTAL_CODE VARCHAR2(10),
ADDRESS_HOUSE2 VARCHAR2(100),
FK_COUNTRY INT NOT NULL,
CELLPHONE VARCHAR2(20),
active varchar2(1) not null,
FK_DEPARTMENT INT NOT NULL,
CONSTRAINT PK_ID_DOCUMENT PRIMARY KEY (ID_DOCUMENT),
FOREIGN KEY (FK_CITY) REFERENCES CITY (ID_CITY)
)TABLESPACE BET_ITM ;

CREATE TABLE DATAUSER (
 ID INT generated always as identity,
ID_USER NUMBER(10) NOT NULL,
BALANCE FLOAT NOT NULL,
BANK_ACCOUNT VARCHAR2(50)NOT NULL,
Status VARCHAR2(1) NOT NULL,
active varchar2(1) not null,
FK_DOCUMENT INT,
CONSTRAINT PK_ID_USER PRIMARY KEY (ID_USER),
FOREIGN KEY (FK_DOCUMENT) REFERENCES DOCUMENT_USER (ID_DOCUMENT)
)TABLESPACE BET_ITM; 

CREATE TABLE WITHDRAW (
 ID INT generated always as identity,
ID_WITHDRAW NUMBER(10) NOT NULL,
DATE_WITHDRAW TIMESTAMP NOT NULL,
DATE_OUTLAY TIMESTAMP NOT NULL,
APPROVED VARCHAR2(1) NOT NULL,
active varchar2(1) not null,
FK_USER INT,
CONSTRAINT PK_ID_WITHDRAW PRIMARY KEY (ID_WITHDRAW),
FOREIGN KEY (FK_USER) REFERENCES DATAUSER (ID_USER)
)TABLESPACE BET_ITM; 


CREATE TABLE PROOF (
 ID INT generated always as identity,
ID_PROOF NUMBER(10) NOT NULL,
NAME_PROOF VARCHAR2(100) NOT NULL,
PHOTO VARCHAR2(500) NOT NULL,
APPROVED VARCHAR2(1) NOT NULL,
active varchar2(1) not null,
FK_WITHDRAW INT,
CONSTRAINT PK_ID_PROOF PRIMARY KEY (ID_PROOF),
FOREIGN KEY (FK_WITHDRAW) REFERENCES WITHDRAW (ID_WITHDRAW)
)TABLESPACE BET_ITM; 

CREATE TABLE BONUS (
 ID INT generated always as identity,
ID_BONUS NUMBER(10) NOT NULL,
CODE VARCHAR2(100) NOT NULL,
VALIDITY TIMESTAMP NOT NULL,
APPROVED VARCHAR2(1) NOT NULL,
active varchar2(1) not null,
FK_USER INT,
CONSTRAINT PK_ID_BONUS PRIMARY KEY (ID_BONUS),
FOREIGN KEY (FK_USER) REFERENCES DATAUSER (ID_USER)
)TABLESPACE BET_ITM; 

CREATE TABLE PREFERENCES (
 ID INT generated always as identity,
ID_PREFERENCES NUMBER(10) NOT NULL,
NAME_PREFERENCE VARCHAR2(100) NOT NULL,
APPROVED VARCHAR2(1) NOT NULL,
active varchar2(1) not null,
FK_USER INT,
CONSTRAINT PK_ID_PREFERENCES PRIMARY KEY (ID_PREFERENCES),
FOREIGN KEY (FK_USER) REFERENCES DATAUSER (ID_USER)
)TABLESPACE BET_ITM; 

CREATE TABLE PAYMENT_CLASS (
 ID INT generated always as identity,
ID_PAYMENT_CLASS NUMBER(10) NOT NULL,
NAME_PAYMENT VARCHAR2(100) NOT NULL,
MINIMUM_VALUE FLOAT NOT NULL,
MAXIIMUM_VALUE FLOAT NOT NULL,
active varchar2(1) not null,
CONSTRAINT PK_ID_PAYMENT_CLASS PRIMARY KEY (ID_PAYMENT_CLASS)
)TABLESPACE BET_ITM; 

CREATE TABLE DEPOSIT (
 ID INT generated always as identity,
ID_DEPOSIT NUMBER(10) NOT NULL,
TRANSACTION_DATE TIMESTAMP NOT NULL,
STATUS VARCHAR2(50) NOT NULL,
active varchar2(1) not null,
FK_USER INT,
FK_PAYMENT_CLASS INT,
CONSTRAINT PK_ID_DEPOSIT PRIMARY KEY (ID_DEPOSIT),
FOREIGN KEY (FK_USER) REFERENCES DATAUSER (ID_USER),
FOREIGN KEY (FK_PAYMENT_CLASS) REFERENCES PAYMENT_CLASS (ID_PAYMENT_CLASS)
)TABLESPACE BET_ITM; 

CREATE TABLE LIMIT_DEPOSIT (
 ID INT generated always as identity,
ID_LIMIT_DEPOSIT NUMBER(10) NOT NULL,
MAXIMUM_DAILY FLOAT,
    CONSTRAINT CK_DAILY_NOT_ZERO
    CHECK(MAXIMUM_DAILY >0 ),
    CONSTRAINT CK_DAILY_MINOR
    CHECK(MAXIMUM_DAILY < MAXIMUM_MONTHLY AND MAXIMUM_DAILY < MAXIMUM_WEEKLY),
MAXIMUM_WEEKLY FLOAT ,
    CONSTRAINT CK_WEEKLY_NOT_ZERO
    CHECK(MAXIMUM_WEEKLY>0),
    CONSTRAINT CK_WEEKLY_MINOR
    CHECK(MAXIMUM_WEEKLY < MAXIMUM_MONTHLY AND MAXIMUM_WEEKLY > MAXIMUM_DAILY),
MAXIMUM_MONTHLY FLOAT,
    CONSTRAINT CK_MONTHLY_NOT_ZERO
    CHECK(MAXIIMUM_MONTHLY>0),
    CONSTRAINT CK_MONTHLY_GREATER
    CHECK(MAXIMUM_MONTHLY > MAXIMUM_WEEKLY AND MAXIMUM_MONTHLY > MAXIMUM_DAILY),
    active varchar2(1) not null,
UPDATE_DATE TIMESTAMP NOT NULL,
CLOSE_DATE TIMESTAMP NOT NULL,
FK_DATAUSER INT,
CONSTRAINT PK_ID_LIMIT_DEPOSIT PRIMARY KEY (ID_LIMIT_DEPOSIT),
FOREIGN KEY (FK_DATAUSER) REFERENCES DATAUSER (ID_USER)
)
TABLESPACE BET_ITM; 

CREATE TABLE BET (
 ID INT generated always as identity,
ID_BET NUMBER(10) NOT NULL,
creation_date TIMESTAMP,
total_value float,
total_profit float,
status varchar(10),
active varchar2(1) not null,
FK_DATAUSER INT,
CONSTRAINT PK_datauser PRIMARY KEY (ID_bet),
FOREIGN KEY (FK_datauser) REFERENCES datauser (ID_user)
)TABLESPACE BET_ITM; 


create table bet_category
(
 ID INT generated always as identity,
id_bet_category number(10) not null,
name_category varchar(100) not null,
active varchar2(1) not null
)tablespace bet_itm


create table macht
(
 ID INT generated always as identity,
id_macht number(10) not null,
team1 varchar2(150),
team2 varchar2(150),
match_date timestamp,
status varchar2(10),
total_goal int,
goals_team1_halftime int,
goals_team2_halftime int,
total_goals_team1 int,
total_goals_team2 int,
active varchar2(1) not null
)tablespace bet_itm



create table quota_macht
(
 ID INT generated always as identity,
id_quota_macht number(10) not null,
quota_1 float not null,
quota_2 float not null,
quota_3 float not null,
winner_quota int not null,
active varchar2(1) not null,
fk_match int,
fk_bet_category int,
constraint pk_quota_macht primary key(id_quota_macht),
foreign key(fk_match) references macht(id_match),
foreign key(fk_bet_category) references bet_category(id_bet_category)
)tablespace bet_itm


create table bet_detail
(
 ID INT generated always as identity,
id_bet_detail number(10) not null,
winner_opcion varchar(10) not null,
bet_quota float not null,
bet_value float not null,
status varchar(10),
active varchar2(1) not null,
fk_quota_macht int,
fk_bet int,
constraint pk_quota_macht primary key(id_bet_detail),
foreign key(fk_quota_macht) references quota_macht(id_quota_macht),
foreign key(fk_bet) references bet(id_bet)
)tablespace bet_itm

create table transactions
(
 ID INT generated always as identity,
id_transactions number(10) not null,
descriptions varchar2(200) not null,
type_transactions varchar2(100),
status varchar(10),
transaction_value float,
active varchar2(1) not null,
fk_user int,
constraint pk_transactions primary key(id_transactions),
foreign key(fk_user) references datauser(id_user)
)tablespace bet_itm


create table columnas_
(
ID INT generated always as identity,
id_columnas number,
dateandtime timestamp,
table_ varchar2(20),
record_id int,
action varchar(10),
user_ varchar(50),
ip varchar2(18),
active varchar2(1) not null
)tablespace BET_AUDITING

select * from columnas;

drop table BET;
drop table GAME;
drop table TEAM;
drop table STATUS;
drop table BET_CLASS;
drop table LIMIT_DEPOSIT;
drop table DEPOSIT;
drop table PAYMENT_CLASS;
drop table PREFERENCES;
drop table BONUS;
drop table PROOF;
drop table WITHDRAW;
drop table DATAUSER;
drop table DOCUMENT_USER;
drop table CITY;
drop table DEPARTMENT;
drop table COUNTRY;



















